using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Program.DATA.Entities;
using Program.DATA.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Program.DAL.SeedData
{
    public class SeedNutritions : IEntityTypeConfiguration<Nutrition>
    {
        public void Configure(EntityTypeBuilder<Nutrition> builder)
        {
            builder.HasData
                (
                new Nutrition { ID = 1, CategoryID = 1, Name = "Artichoke", PortionType = PortionType.Unit, Calorie = 60, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\1.jpg" },
                new Nutrition { ID = 2, CategoryID = 1, Name = "Arugula", PortionType = PortionType.Gram, Calorie = 50, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\2.jpg" },
                new Nutrition { ID = 3, CategoryID = 1, Name = "Asparagus", PortionType = PortionType.Unit, Calorie = 2, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\3.jpg" },
                new Nutrition { ID = 4, CategoryID = 1, Name = "Aubergine", PortionType = PortionType.Unit, Calorie = 115, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\4.jpg" },
                new Nutrition { ID = 5, CategoryID = 1, Name = "Beetroot", PortionType = PortionType.Unit, Calorie = 35, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\5.jpg" },
                new Nutrition { ID = 6, CategoryID = 1, Name = "Bell Pepper", PortionType = PortionType.Unit, Calorie = 15, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\6.jpg" },
                new Nutrition { ID = 7, CategoryID = 1, Name = "Black Olives", PortionType = PortionType.Unit, Calorie = 2, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\7.jpg" },
                new Nutrition { ID = 8, CategoryID = 1, Name = "Broccoli", PortionType = PortionType.Gram, Calorie = 35, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\8.jpg" },
                new Nutrition { ID = 9, CategoryID = 1, Name = "Brussels Sprouts", PortionType = PortionType.Gram, Calorie = 40, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\9.jpg" },
                new Nutrition { ID = 10, CategoryID = 1, Name = "Cabbage", PortionType = PortionType.Floweret, Calorie = 227, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\10.jpg" },
                new Nutrition { ID = 11, CategoryID = 1, Name = "Capsicum", PortionType = PortionType.Unit, Calorie = 12, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\11.jpg" },
                new Nutrition { ID = 12, CategoryID = 1, Name = "Carrot", PortionType = PortionType.Unit, Calorie = 25, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\12.jpg" },
                new Nutrition { ID = 13, CategoryID = 1, Name = "Cauliflower", PortionType = PortionType.Floweret, Calorie = 3, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\13.jpg" },
                new Nutrition { ID = 14, CategoryID = 1, Name = "Celery", PortionType = PortionType.Plate, Calorie = 42, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\14.jpg" },
                new Nutrition { ID = 15, CategoryID = 1, Name = "Cherry Tomato", PortionType = PortionType.Unit, Calorie = 20, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\15.jpg" },
                new Nutrition { ID = 16, CategoryID = 1, Name = "Chinese Cabbage", PortionType = PortionType.Floweret, Calorie = 134, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\16.jpg" },
                new Nutrition { ID = 17, CategoryID = 1, Name = "Collard Greens", PortionType = PortionType.Gram, Calorie = 32, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\17.jpg" },
                new Nutrition { ID = 18, CategoryID = 1, Name = "Corn", PortionType = PortionType.Unit, Calorie = 96, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\18.jpg" },
                new Nutrition { ID = 19, CategoryID = 1, Name = "Courgette", PortionType = PortionType.Gram, Calorie = 20, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\19.jpg" },
                new Nutrition { ID = 20, CategoryID = 1, Name = "Cucumber", PortionType = PortionType.Unit, Calorie = 15, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\20.jpg" },
                new Nutrition { ID = 21, CategoryID = 11, Name = "Salami", PortionType = PortionType.Gram, Calorie = 336, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\21.jpg" },
                new Nutrition { ID = 22, CategoryID = 1, Name = "Endive", PortionType = PortionType.Gram, Calorie = 17, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\22.jpg" },
                new Nutrition { ID = 23, CategoryID = 1, Name = "Fennel", PortionType = PortionType.Gram, Calorie = 32, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\23.jpg" },
                new Nutrition { ID = 24, CategoryID = 1, Name = "Garlic", PortionType = PortionType.Unit, Calorie = 4, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\24.jpg" },
                new Nutrition { ID = 25, CategoryID = 1, Name = "Gherkin", PortionType = PortionType.Unit, Calorie = 9, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\25.jpg" },
                new Nutrition { ID = 26, CategoryID = 1, Name = "Gourd", PortionType = PortionType.Unit, Calorie = 108, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\26.jpg" },
                new Nutrition { ID = 27, CategoryID = 1, Name = "Green Beans", PortionType = PortionType.Gram, Calorie = 32, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\27.jpg" },
                new Nutrition { ID = 28, CategoryID = 1, Name = "Green Olives", PortionType = PortionType.Unit, Calorie = 2, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\28.jpg" },
                new Nutrition { ID = 29, CategoryID = 1, Name = "Green Onion", PortionType = PortionType.Unit, Calorie = 5, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\29.jpg" },
                new Nutrition { ID = 30, CategoryID = 1, Name = "Horseradish", PortionType = PortionType.Gram, Calorie = 7, IsActive = true, Measurement = 5, Picture = "\\FoodPhotos\\30.jpg" },
                new Nutrition { ID = 31, CategoryID = 1, Name = "Kale", PortionType = PortionType.Gram, Calorie = 43, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\31.jpg" },
                new Nutrition { ID = 32, CategoryID = 1, Name = "Leek", PortionType = PortionType.Unit, Calorie = 54, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\32.jpg" },
                new Nutrition { ID = 33, CategoryID = 1, Name = "Lettuce", PortionType = PortionType.Unit, Calorie = 109, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\33.jpg" },
                new Nutrition { ID = 34, CategoryID = 1, Name = "Mushrooms", PortionType = PortionType.Unit, Calorie = 1, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\34.jpg" },
                new Nutrition { ID = 35, CategoryID = 1, Name = "Mustard Greens", PortionType = PortionType.Gram, Calorie = 28, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\35.jpg" },
                new Nutrition { ID = 36, CategoryID = 1, Name = "Okra", PortionType = PortionType.Gram, Calorie = 33, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\36.jpg" },
                new Nutrition { ID = 37, CategoryID = 11, Name = "Sausage", PortionType = PortionType.Gram, Calorie = 300, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\37.jpg" },
                new Nutrition { ID = 38, CategoryID = 1, Name = "Onion", PortionType = PortionType.Unit, Calorie = 34, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\38.jpg" },
                new Nutrition { ID = 39, CategoryID = 1, Name = "Parsnips", PortionType = PortionType.Unit, Calorie = 128, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\39.jpg" },
                new Nutrition { ID = 40, CategoryID = 1, Name = "Peas", PortionType = PortionType.Gram, Calorie = 81, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\40.jpg" },
                new Nutrition { ID = 41, CategoryID = 11, Name = "Bacon", PortionType = PortionType.Slice, Calorie = 29, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\41.jpg" },
                new Nutrition { ID = 42, CategoryID = 1, Name = "Potato", PortionType = PortionType.Unit, Calorie = 164, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\42.jpg" },
                new Nutrition { ID = 43, CategoryID = 1, Name = "Pumpkin", PortionType = PortionType.Unit, Calorie = 51, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\43.jpg" },
                new Nutrition { ID = 44, CategoryID = 1, Name = "Radishes", PortionType = PortionType.Unit, Calorie = 15, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\44.jpg" },
                new Nutrition { ID = 45, CategoryID = 1, Name = "Red Cabbage", PortionType = PortionType.Unit, Calorie = 260, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\45.jpg" },
                new Nutrition { ID = 46, CategoryID = 1, Name = "Rutabaga", PortionType = PortionType.Unit, Calorie = 147, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\46.jpg" },
                new Nutrition { ID = 47, CategoryID = 1, Name = "Shallots", PortionType = PortionType.Unit, Calorie = 18, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\47.jpg" },
                new Nutrition { ID = 48, CategoryID = 1, Name = "Squash", PortionType = PortionType.Unit, Calorie = 130, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\48.jpg" },
                new Nutrition { ID = 49, CategoryID = 1, Name = "Sweet Potato", PortionType = PortionType.Unit, Calorie = 112, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\49.jpg" },
                new Nutrition { ID = 50, CategoryID = 1, Name = "Tomato", PortionType = PortionType.Unit, Calorie = 20, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\50.jpg" },
                new Nutrition { ID = 51, CategoryID = 1, Name = "Turnip", PortionType = PortionType.Unit, Calorie = 34, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\51.jpg" },
                new Nutrition { ID = 52, CategoryID = 2, Name = "Apple", PortionType = PortionType.Unit, Calorie = 95, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\52.jpg" },
                new Nutrition { ID = 53, CategoryID = 2, Name = "Apricot", PortionType = PortionType.Unit, Calorie = 17, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\53.jpg" },
                new Nutrition { ID = 54, CategoryID = 2, Name = "Avocado", PortionType = PortionType.Unit, Calorie = 240, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\54.jpg" },
                new Nutrition { ID = 55, CategoryID = 2, Name = "Banana", PortionType = PortionType.Unit, Calorie = 111, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\55.jpg" },
                new Nutrition { ID = 56, CategoryID = 2, Name = "Blackberries", PortionType = PortionType.Gram, Calorie = 43, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\56.jpg" },
                new Nutrition { ID = 57, CategoryID = 2, Name = "Blood Oranges", PortionType = PortionType.Unit, Calorie = 70, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\57.jpg" },
                new Nutrition { ID = 58, CategoryID = 2, Name = "Blueberries", PortionType = PortionType.Gram, Calorie = 84, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\58.jpg" },
                new Nutrition { ID = 59, CategoryID = 2, Name = "Cantaloupe", PortionType = PortionType.Gram, Calorie = 34, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\59.jpg" },
                new Nutrition { ID = 60, CategoryID = 2, Name = "Cherries", PortionType = PortionType.Unit, Calorie = 4, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\60.jpg" },
                new Nutrition { ID = 61, CategoryID = 2, Name = "Cranberries", PortionType = PortionType.Gram, Calorie = 46, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\61.jpg" },
                new Nutrition { ID = 62, CategoryID = 2, Name = "Dates", PortionType = PortionType.Unit, Calorie = 20, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\62.jpg" },
                new Nutrition { ID = 63, CategoryID = 2, Name = "Figs", PortionType = PortionType.Unit, Calorie = 37, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\63.jpg" },
                new Nutrition { ID = 64, CategoryID = 7, Name = "Fruit salad", PortionType = PortionType.Bowl, Calorie = 125, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\64.jpg" },
                new Nutrition { ID = 65, CategoryID = 2, Name = "Grapes", PortionType = PortionType.Gram, Calorie = 67, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\65.jpg" },
                new Nutrition { ID = 66, CategoryID = 2, Name = "Kiwi", PortionType = PortionType.Unit, Calorie = 112, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\66.jpg" },
                new Nutrition { ID = 67, CategoryID = 2, Name = "Lemon", PortionType = PortionType.Unit, Calorie = 17, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\67.jpg" },
                new Nutrition { ID = 68, CategoryID = 2, Name = "Lime", PortionType = PortionType.Unit, Calorie = 20, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\68.jpg" },
                new Nutrition { ID = 69, CategoryID = 2, Name = "Lychees", PortionType = PortionType.Unit, Calorie = 7, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\69.jpg" },
                new Nutrition { ID = 70, CategoryID = 2, Name = "Mandarin Oranges", PortionType = PortionType.Unit, Calorie = 47, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\70.jpg" },
                new Nutrition { ID = 71, CategoryID = 2, Name = "Mango", PortionType = PortionType.Unit, Calorie = 202, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\71.jpg" },
                new Nutrition { ID = 72, CategoryID = 2, Name = "Nectarine", PortionType = PortionType.Unit, Calorie = 66, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\72.jpg" },
                new Nutrition { ID = 73, CategoryID = 2, Name = "Orange", PortionType = PortionType.Unit, Calorie = 62, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\73.jpg" },
                new Nutrition { ID = 74, CategoryID = 2, Name = "Papaya", PortionType = PortionType.Unit, Calorie = 215, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\74.jpg" },
                new Nutrition { ID = 75, CategoryID = 2, Name = "Passion Fruit", PortionType = PortionType.Unit, Calorie = 17, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\75.jpg" },
                new Nutrition { ID = 76, CategoryID = 2, Name = "Peach", PortionType = PortionType.Unit, Calorie = 59, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\76.jpg" },
                new Nutrition { ID = 77, CategoryID = 2, Name = "Pear", PortionType = PortionType.Unit, Calorie = 101, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\77.jpg" },
                new Nutrition { ID = 78, CategoryID = 2, Name = "Pineapple", PortionType = PortionType.Gram, Calorie = 50, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\78.jpg" },
                new Nutrition { ID = 79, CategoryID = 2, Name = "Plum", PortionType = PortionType.Unit, Calorie = 30, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\79.jpg" },
                new Nutrition { ID = 80, CategoryID = 2, Name = "Pomegranate", PortionType = PortionType.Unit, Calorie = 234, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\80.jpg" },
                new Nutrition { ID = 81, CategoryID = 5, Name = "Raisins", PortionType = PortionType.Gram, Calorie = 300, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\81.jpg" },
                new Nutrition { ID = 82, CategoryID = 2, Name = "Raspberries", PortionType = PortionType.Bowl, Calorie = 64, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\82.jpg" },
                new Nutrition { ID = 83, CategoryID = 2, Name = "Strawberries", PortionType = PortionType.Bowl, Calorie = 49, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\83.jpg" },
                new Nutrition { ID = 84, CategoryID = 2, Name = "Tangerine", PortionType = PortionType.Unit, Calorie = 47, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\84.jpg" },
                new Nutrition { ID = 85, CategoryID = 2, Name = "Watermelon", PortionType = PortionType.Slice, Calorie = 86, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\85.jpg" },
                new Nutrition { ID = 86, CategoryID = 8, Name = "Bacon and Eggs", PortionType = PortionType.Serving, Calorie = 680, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\86.jpg" },
                new Nutrition { ID = 87, CategoryID = 12, Name = "Baked Beans", PortionType = PortionType.Gram, Calorie = 150, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\87.jpg" },
                new Nutrition { ID = 88, CategoryID = 11, Name = "BBQ Ribs", PortionType = PortionType.Unit, Calorie = 360, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\88.jpg" },
                new Nutrition { ID = 89, CategoryID = 11, Name = "Beef Stew", PortionType = PortionType.Bowl, Calorie = 186, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\89.jpg" },
                new Nutrition { ID = 90, CategoryID = 12, Name = "Black Rice", PortionType = PortionType.Gram, Calorie = 170, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\90.jpg" },
                new Nutrition { ID = 91, CategoryID = 12, Name = "Brown Rice", PortionType = PortionType.Gram, Calorie = 110, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\91.jpg" },
                new Nutrition { ID = 92, CategoryID = 10, Name = "Burrito", PortionType = PortionType.Unit, Calorie = 326, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\92.jpg" },
                new Nutrition { ID = 93, CategoryID = 9, Name = "California Roll", PortionType = PortionType.Unit, Calorie = 33, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\93.jpg" },
                new Nutrition { ID = 94, CategoryID = 7, Name = "Chicken Caesar Salad", PortionType = PortionType.Bowl, Calorie = 309, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\94.jpg" },
                new Nutrition { ID = 95, CategoryID = 11, Name = "Chicken Marsala", PortionType = PortionType.Serving, Calorie = 290, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\95.jpg" },
                new Nutrition { ID = 96, CategoryID = 11, Name = "Chicken Tikka Masala", PortionType = PortionType.Serving, Calorie = 350, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\96.jpg" },
                new Nutrition { ID = 97, CategoryID = 11, Name = "Chimichanga", PortionType = PortionType.Unit, Calorie = 308, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\97.jpg" },
                new Nutrition { ID = 98, CategoryID = 7, Name = "Cobb Salad", PortionType = PortionType.Bowl, Calorie = 160, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\98.jpg" },
                new Nutrition { ID = 99, CategoryID = 10, Name = "Corn Dog", PortionType = PortionType.Unit, Calorie = 180, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\99.jpg" },
                new Nutrition { ID = 100, CategoryID = 6, Name = "Cottage Pie", PortionType = PortionType.Slice, Calorie = 300, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\100.jpg" },
                new Nutrition { ID = 101, CategoryID = 11, Name = "Enchiladas", PortionType = PortionType.Unit, Calorie = 323, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\101.jpg" },
                new Nutrition { ID = 102, CategoryID = 11, Name = "Fajita", PortionType = PortionType.Serving, Calorie = 290, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\102.jpg" },
                new Nutrition { ID = 103, CategoryID = 9, Name = "Fish and Chips", PortionType = PortionType.Serving, Calorie = 585, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\103.jpg" },
                new Nutrition { ID = 104, CategoryID = 12, Name = "Fried Rice", PortionType = PortionType.Serving, Calorie = 662, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\104.jpg" },
                new Nutrition { ID = 105, CategoryID = 9, Name = "Fried Shrimp", PortionType = PortionType.Unit, Calorie = 75, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\105.jpg" },
                new Nutrition { ID = 106, CategoryID = 10, Name = "Grilled Cheese Sandwich", PortionType = PortionType.Serving, Calorie = 392, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\106.jpg" },
                new Nutrition { ID = 107, CategoryID = 10, Name = "Ham and Cheese Sandwich", PortionType = PortionType.Serving, Calorie = 352, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\107.jpg" },
                new Nutrition { ID = 108, CategoryID = 11, Name = "Kebab", PortionType = PortionType.Serving, Calorie = 774, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\108.jpg" },
                new Nutrition { ID = 109, CategoryID = 10, Name = "Lasagne", PortionType = PortionType.Serving, Calorie = 284, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\109.jpg" },
                new Nutrition { ID = 110, CategoryID = 10, Name = "Mac and Cheese", PortionType = PortionType.Serving, Calorie = 699, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\110.jpg" },
                new Nutrition { ID = 111, CategoryID = 11, Name = "Orange Chicken", PortionType = PortionType.Serving, Calorie = 420, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\111.jpg" },
                new Nutrition { ID = 112, CategoryID = 10, Name = "Pad Thai", PortionType = PortionType.Bowl, Calorie = 375, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\112.jpg" },
                new Nutrition { ID = 113, CategoryID = 13, Name = "Pea Soup", PortionType = PortionType.Bowl, Calorie = 190, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\113.jpg" },
                new Nutrition { ID = 114, CategoryID = 10, Name = "Peanut Butter Sandwich", PortionType = PortionType.Unit, Calorie = 200, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\114.jpg" },
                new Nutrition { ID = 115, CategoryID = 11, Name = "Philly Cheese Steak", PortionType = PortionType.Unit, Calorie = 300, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\115.jpg" },
                new Nutrition { ID = 116, CategoryID = 10, Name = "Pizza", PortionType = PortionType.Slice, Calorie = 272, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\116.jpg" },
                new Nutrition { ID = 117, CategoryID = 7, Name = "Potato Salad", PortionType = PortionType.Bowl, Calorie = 300, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\117.jpg" },
                new Nutrition { ID = 118, CategoryID = 10, Name = "Ramen", PortionType = PortionType.Bowl, Calorie = 500, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\118.jpg" },
                new Nutrition { ID = 119, CategoryID = 10, Name = "Ravioli", PortionType = PortionType.Serving, Calorie = 370, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\119.jpg" },
                new Nutrition { ID = 120, CategoryID = 10, Name = "Reuben Sandwich", PortionType = PortionType.Unit, Calorie = 641, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\120.jpg" },
                new Nutrition { ID = 121, CategoryID = 11, Name = "Roast Beef", PortionType = PortionType.Slice, Calorie = 110, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\121.jpg" },
                new Nutrition { ID = 122, CategoryID = 10, Name = "Spaghetti Bolognese", PortionType = PortionType.Serving, Calorie = 374, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\122.jpg" },
                new Nutrition { ID = 123, CategoryID = 10, Name = "Taco", PortionType = PortionType.Unit, Calorie = 213, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\123.jpg" },
                new Nutrition { ID = 124, CategoryID = 10, Name = "BBQ Chicken Pizza", PortionType = PortionType.Slice, Calorie = 309, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\124.jpg" },
                new Nutrition { ID = 125, CategoryID = 10, Name = "BBQ Pizza", PortionType = PortionType.Slice, Calorie = 314, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\125.jpg" },
                new Nutrition { ID = 126, CategoryID = 10, Name = "Beef Pizza", PortionType = PortionType.Slice, Calorie = 714, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\126.jpg" },
                new Nutrition { ID = 127, CategoryID = 10, Name = "Bianca Pizza", PortionType = PortionType.Slice, Calorie = 460, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\127.jpg" },
                new Nutrition { ID = 128, CategoryID = 10, Name = "Buffalo Chicken Pizza", PortionType = PortionType.Slice, Calorie = 600, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\128.jpg" },
                new Nutrition { ID = 129, CategoryID = 10, Name = "Cheese Pizza", PortionType = PortionType.Slice, Calorie = 168, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\129.jpg" },
                new Nutrition { ID = 130, CategoryID = 10, Name = "Chicken Pizza", PortionType = PortionType.Slice, Calorie = 309, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\130.jpg" },
                new Nutrition { ID = 131, CategoryID = 10, Name = "Deep Dish Pizza", PortionType = PortionType.Slice, Calorie = 313, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\131.jpg" },
                new Nutrition { ID = 132, CategoryID = 10, Name = "Goat Cheese Pizza", PortionType = PortionType.Slice, Calorie = 138, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\132.jpg" },
                new Nutrition { ID = 133, CategoryID = 10, Name = "Grilled Pizza", PortionType = PortionType.Slice, Calorie = 280, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\133.jpg" },
                new Nutrition { ID = 134, CategoryID = 10, Name = "Hawaiian Pizza", PortionType = PortionType.Slice, Calorie = 154, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\134.jpg" },
                new Nutrition { ID = 135, CategoryID = 10, Name = "Margherita Pizza", PortionType = PortionType.Slice, Calorie = 173, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\135.jpg" },
                new Nutrition { ID = 136, CategoryID = 10, Name = "Mozzarella Pizza", PortionType = PortionType.Slice, Calorie = 154, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\136.jpg" },
                new Nutrition { ID = 137, CategoryID = 10, Name = "Mushroom Pizza", PortionType = PortionType.Slice, Calorie = 611, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\137.jpg" },
                new Nutrition { ID = 138, CategoryID = 10, Name = "Napoli Pizza", PortionType = PortionType.Slice, Calorie = 248, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\138.jpg" },
                new Nutrition { ID = 139, CategoryID = 10, Name = "New York Style Pizza", PortionType = PortionType.Slice, Calorie = 174, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\139.jpg" },
                new Nutrition { ID = 140, CategoryID = 10, Name = "Pepperoni Pizza", PortionType = PortionType.Slice, Calorie = 181, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\140.jpg" },
                new Nutrition { ID = 141, CategoryID = 10, Name = "Pizza Hut Stuffed Crust Pizza", PortionType = PortionType.Slice, Calorie = 380, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\141.jpg" },
                new Nutrition { ID = 142, CategoryID = 10, Name = "Pizza Hut Supreme Pizza", PortionType = PortionType.Slice, Calorie = 305, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\142.jpg" },
                new Nutrition { ID = 143, CategoryID = 10, Name = "Quattro Formaggi Pizza", PortionType = PortionType.Slice, Calorie = 330, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\143.jpg" },
                new Nutrition { ID = 144, CategoryID = 10, Name = "Red Pepper Pizza", PortionType = PortionType.Slice, Calorie = 165, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\144.jpg" },
                new Nutrition { ID = 145, CategoryID = 10, Name = "Salami Pizza", PortionType = PortionType.Slice, Calorie = 181, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\145.jpg" },
                new Nutrition { ID = 146, CategoryID = 10, Name = "Sausage Pizza", PortionType = PortionType.Slice, Calorie = 177, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\146.jpg" },
                new Nutrition { ID = 147, CategoryID = 10, Name = "Seafood Pizza", PortionType = PortionType.Slice, Calorie = 186, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\147.jpg" },
                new Nutrition { ID = 148, CategoryID = 10, Name = "Shrimp Pizza", PortionType = PortionType.Slice, Calorie = 190, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\148.jpg" },
                new Nutrition { ID = 149, CategoryID = 10, Name = "Sicilian Pizza", PortionType = PortionType.Slice, Calorie = 321, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\149.jpg" },
                new Nutrition { ID = 150, CategoryID = 10, Name = "Spinach Feta Pizza", PortionType = PortionType.Slice, Calorie = 150, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\150.jpg" },
                new Nutrition { ID = 151, CategoryID = 10, Name = "Spinach Pizza", PortionType = PortionType.Slice, Calorie = 145, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\151.jpg" },
                new Nutrition { ID = 152, CategoryID = 10, Name = "Stuffed Crust Pizza", PortionType = PortionType.Slice, Calorie = 380, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\152.jpg" },
                new Nutrition { ID = 153, CategoryID = 10, Name = "Thin Crust Pizza", PortionType = PortionType.Slice, Calorie = 157, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\153.jpg" },
                new Nutrition { ID = 154, CategoryID = 10, Name = "Tuna Pizza", PortionType = PortionType.Slice, Calorie = 318, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\154.jpg" },
                new Nutrition { ID = 155, CategoryID = 10, Name = "Veggie Pizza", PortionType = PortionType.Slice, Calorie = 263, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\155.jpg" },
                new Nutrition { ID = 156, CategoryID = 10, Name = "Burger King Angry Whopper", PortionType = PortionType.Unit, Calorie = 740, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\156.jpg" },
                new Nutrition { ID = 157, CategoryID = 10, Name = "Burger King Double Whopper", PortionType = PortionType.Unit, Calorie = 894, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\157.jpg" },
                new Nutrition { ID = 158, CategoryID = 10, Name = "Burger King Double Whopper with Cheese", PortionType = PortionType.Unit, Calorie = 994, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\158.jpg" },
                new Nutrition { ID = 159, CategoryID = 10, Name = "Burger King Original Chicken Sandwich", PortionType = PortionType.Unit, Calorie = 659, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\159.jpg" },
                new Nutrition { ID = 160, CategoryID = 10, Name = "Burger King Premium Alaskan Fish Sandwich", PortionType = PortionType.Unit, Calorie = 591, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\160.jpg" },
                new Nutrition { ID = 161, CategoryID = 10, Name = "Burger King Triple Whopper", PortionType = PortionType.Unit, Calorie = 1471, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\161.jpg" },
                new Nutrition { ID = 162, CategoryID = 10, Name = "Burger King Whopper", PortionType = PortionType.Unit, Calorie = 672, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\162.jpg" },
                new Nutrition { ID = 163, CategoryID = 10, Name = "Burger King Whopper Jr.", PortionType = PortionType.Unit, Calorie = 346, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\163.jpg" },
                new Nutrition { ID = 164, CategoryID = 10, Name = "Burger King Whopper with Cheese", PortionType = PortionType.Unit, Calorie = 759, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\164.jpg" },
                new Nutrition { ID = 165, CategoryID = 10, Name = "Cheeseburger", PortionType = PortionType.Unit, Calorie = 410, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\165.jpg" },
                new Nutrition { ID = 166, CategoryID = 11, Name = "Chicken Breast", PortionType = PortionType.Gram, Calorie = 170, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\166.jpg" },
                new Nutrition { ID = 167, CategoryID = 10, Name = "Chicken Nuggets", PortionType = PortionType.Unit, Calorie = 59, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\167.jpg" },
                new Nutrition { ID = 168, CategoryID = 10, Name = "Chicken Sandwich", PortionType = PortionType.Unit, Calorie = 410, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\168.jpg" },
                new Nutrition { ID = 169, CategoryID = 10, Name = "Chicken Teriyaki Sandwich", PortionType = PortionType.Unit, Calorie = 367, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\169.jpg" },
                new Nutrition { ID = 170, CategoryID = 10, Name = "Chicken Wings", PortionType = PortionType.Unit, Calorie = 94, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\170.jpg" },
                new Nutrition { ID = 171, CategoryID = 10, Name = "Curly Fries", PortionType = PortionType.Serving, Calorie = 398, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\171.jpg" },
                new Nutrition { ID = 172, CategoryID = 10, Name = "Double Cheeseburger", PortionType = PortionType.Unit, Calorie = 414, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\172.jpg" },
                new Nutrition { ID = 173, CategoryID = 10, Name = "French Fries", PortionType = PortionType.Serving, Calorie = 222, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\173.jpg" },
                new Nutrition { ID = 174, CategoryID = 7, Name = "Grilled Chicken Salad", PortionType = PortionType.Bowl, Calorie = 268, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\174.jpg" },
                new Nutrition { ID = 175, CategoryID = 10, Name = "Hamburger", PortionType = PortionType.Unit, Calorie = 279, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\175.jpg" },
                new Nutrition { ID = 176, CategoryID = 10, Name = "Hot Dog", PortionType = PortionType.Unit, Calorie = 312, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\176.jpg" },
                new Nutrition { ID = 177, CategoryID = 10, Name = "Meatball Sandwich", PortionType = PortionType.Unit, Calorie = 481, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\177.jpg" },
                new Nutrition { ID = 178, CategoryID = 10, Name = "Onion Rings", PortionType = PortionType.Unit, Calorie = 25, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\178.jpg" },
                new Nutrition { ID = 179, CategoryID = 9, Name = "Smoked Salmon", PortionType = PortionType.Gram, Calorie = 195, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\179.jpg" },
                new Nutrition { ID = 180, CategoryID = 10, Name = "Subway Club Sandwich", PortionType = PortionType.Unit, Calorie = 312, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\180.jpg" },
                new Nutrition { ID = 181, CategoryID = 10, Name = "Tortilla Wrap", PortionType = PortionType.Unit, Calorie = 171, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\181.jpg" },
                new Nutrition { ID = 182, CategoryID = 9, Name = "Tuna", PortionType = PortionType.Gram, Calorie = 94, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\182.jpg" },
                new Nutrition { ID = 183, CategoryID = 11, Name = "Turkey", PortionType = PortionType.Gram, Calorie = 135, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\183.jpg" },
                new Nutrition { ID = 184, CategoryID = 10, Name = "Veggie Burger", PortionType = PortionType.Unit, Calorie = 389, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\184.jpg" },
                new Nutrition { ID = 185, CategoryID = 10, Name = "Zinger", PortionType = PortionType.Unit, Calorie = 517, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\185.jpg" },
                new Nutrition { ID = 186, CategoryID = 11, Name = "Egg", PortionType = PortionType.Unit, Calorie = 68, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\186.jpg" },
                new Nutrition { ID = 187, CategoryID = 11, Name = "Steak", PortionType = PortionType.Slice, Calorie = 160, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\187.jpg" },
                new Nutrition { ID = 188, CategoryID = 13, Name = "Cornflakes", PortionType = PortionType.Gram, Calorie = 375, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\188.jpg" },
                new Nutrition { ID = 189, CategoryID = 6, Name = "Ice Cream Vanilla", PortionType = PortionType.Bowl, Calorie = 135, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\189.jpg" },
                new Nutrition { ID = 190, CategoryID = 6, Name = "Ice Cream Chocolate", PortionType = PortionType.Bowl, Calorie = 168, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\190.jpg" },
                new Nutrition { ID = 191, CategoryID = 5, Name = "Frozen Yogurt", PortionType = PortionType.Bowl, Calorie = 135, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\191.jpg" },
                new Nutrition { ID = 192, CategoryID = 8, Name = "Yogurt", PortionType = PortionType.Gram, Calorie = 60, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\192.jpg" },
                new Nutrition { ID = 193, CategoryID = 6, Name = "Eclair", PortionType = PortionType.Unit, Calorie = 235, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\193.jpg" },
                new Nutrition { ID = 194, CategoryID = 3, Name = "Milkshake", PortionType = PortionType.Glass, Calorie = 350, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\194.jpg" },
                new Nutrition { ID = 195, CategoryID = 3, Name = "Milkshake Chocolate", PortionType = PortionType.Glass, Calorie = 400, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\195.jpg" },
                new Nutrition { ID = 196, CategoryID = 11, Name = "Pepperoni", PortionType = PortionType.Gram, Calorie = 550, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\196.jpg" },
                new Nutrition { ID = 197, CategoryID = 6, Name = "Macarons", PortionType = PortionType.Unit, Calorie = 55, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\197.jpg" },
                new Nutrition { ID = 198, CategoryID = 13, Name = "Bread", PortionType = PortionType.Slice, Calorie = 75, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\198.jpg" },
                new Nutrition { ID = 199, CategoryID = 6, Name = "Doughnut", PortionType = PortionType.Unit, Calorie = 230, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\199.jpg" },
                new Nutrition { ID = 200, CategoryID = 6, Name = "Doughnut Chocolate", PortionType = PortionType.Unit, Calorie = 380, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\200.jpg" },
                new Nutrition { ID = 201, CategoryID = 3, Name = "Tea", PortionType = PortionType.Glass, Calorie = 2, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\201.jpg" },
                new Nutrition { ID = 202, CategoryID = 13, Name = "Sugar (Cube)", PortionType = PortionType.Unit, Calorie = 11, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\202.jpg" },
                new Nutrition { ID = 203, CategoryID = 13, Name = "Sugar ", PortionType = PortionType.Gram, Calorie = 387, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\203.jpg" },
                new Nutrition { ID = 204, CategoryID = 13, Name = "Sugar Brown", PortionType = PortionType.Gram, Calorie = 373, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\204.jpg" },
                new Nutrition { ID = 205, CategoryID = 6, Name = "Cheesecake", PortionType = PortionType.Slice, Calorie = 329, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\205.jpg" },
                new Nutrition { ID = 206, CategoryID = 6, Name = "Muffin", PortionType = PortionType.Unit, Calorie = 400, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\206.jpg" },
                new Nutrition { ID = 207, CategoryID = 8, Name = "Milk", PortionType = PortionType.Glass, Calorie = 155, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\207.jpg" },
                new Nutrition { ID = 208, CategoryID = 8, Name = "Milk(Non-Fat)", PortionType = PortionType.Glass, Calorie = 87, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\208.jpg" },
                new Nutrition { ID = 209, CategoryID = 6, Name = "Brownie", PortionType = PortionType.Slice, Calorie = 230, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\209.jpg" },
                new Nutrition { ID = 210, CategoryID = 8, Name = "Feta Cheese", PortionType = PortionType.Gram, Calorie = 264, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\210.jpg" },
                new Nutrition { ID = 211, CategoryID = 8, Name = "Cheddar Cheese", PortionType = PortionType.Gram, Calorie = 402, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\211.jpg" },
                new Nutrition { ID = 212, CategoryID = 8, Name = "Mozzarella Cheese", PortionType = PortionType.Gram, Calorie = 280, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\212.jpg" },
                new Nutrition { ID = 213, CategoryID = 8, Name = "Parmesan Cheese", PortionType = PortionType.Gram, Calorie = 430, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\213.jpg" },
                new Nutrition { ID = 214, CategoryID = 8, Name = "Cream Cheese", PortionType = PortionType.Gram, Calorie = 342, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\214.jpg" },
                new Nutrition { ID = 215, CategoryID = 8, Name = "Goat Cheese", PortionType = PortionType.Gram, Calorie = 364, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\215.jpg" },
                new Nutrition { ID = 216, CategoryID = 3, Name = "Coke", PortionType = PortionType.Glass, Calorie = 98, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\216.jpg" },
                new Nutrition { ID = 217, CategoryID = 3, Name = "Coke Zero", PortionType = PortionType.Glass, Calorie = 1, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\217.jpg" },
                new Nutrition { ID = 218, CategoryID = 3, Name = "Americano", PortionType = PortionType.Glass, Calorie = 2, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\218.jpg" },
                new Nutrition { ID = 219, CategoryID = 3, Name = "Espresso", PortionType = PortionType.Glass, Calorie = 2, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\219.jpg" },
                new Nutrition { ID = 220, CategoryID = 3, Name = "Cappuccino", PortionType = PortionType.Glass, Calorie = 70, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\220.jpg" },
                new Nutrition { ID = 221, CategoryID = 3, Name = "Latte", PortionType = PortionType.Glass, Calorie = 120, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\221.jpg" },
                new Nutrition { ID = 222, CategoryID = 3, Name = "Mocha", PortionType = PortionType.Glass, Calorie = 210, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\222.jpg" },
                new Nutrition { ID = 223, CategoryID = 3, Name = "Iced Latte", PortionType = PortionType.Glass, Calorie = 70, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\223.jpg" },
                new Nutrition { ID = 224, CategoryID = 3, Name = "Iced Mocha", PortionType = PortionType.Glass, Calorie = 180, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\224.jpg" },
                new Nutrition { ID = 225, CategoryID = 3, Name = "Frappuccino", PortionType = PortionType.Glass, Calorie = 260, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\225.jpg" },
                new Nutrition { ID = 226, CategoryID = 5, Name = "Chocolate(Bitter)", PortionType = PortionType.Gram, Calorie = 630, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\226.jpg" },
                new Nutrition { ID = 227, CategoryID = 5, Name = "Chocolate(Milk)", PortionType = PortionType.Gram, Calorie = 542, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\227.jpg" },
                new Nutrition { ID = 228, CategoryID = 5, Name = "Chocolate(White)", PortionType = PortionType.Gram, Calorie = 557, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\228.jpg" },
                new Nutrition { ID = 229, CategoryID = 11, Name = "Ground Meat", PortionType = PortionType.Gram, Calorie = 260, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\229.jpg" },
                new Nutrition { ID = 230, CategoryID = 11, Name = "Meatball", PortionType = PortionType.Unit, Calorie = 65, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\230.jpg" },
                new Nutrition { ID = 231, CategoryID = 3, Name = "Mineral Water", PortionType = PortionType.Glass, Calorie = 1, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\231.jpg" },
                new Nutrition { ID = 232, CategoryID = 13, Name = "Olive Oil", PortionType = PortionType.Tablespoon, Calorie = 119, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\232.jpg" },
                new Nutrition { ID = 233, CategoryID = 13, Name = "Canola Oil", PortionType = PortionType.Tablespoon, Calorie = 124, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\233.jpg" },
                new Nutrition { ID = 234, CategoryID = 13, Name = "Sunflower Oil", PortionType = PortionType.Tablespoon, Calorie = 120, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\234.jpg" },
                new Nutrition { ID = 235, CategoryID = 13, Name = "Sesame Oil", PortionType = PortionType.Tablespoon, Calorie = 120, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\235.jpg" },
                new Nutrition { ID = 236, CategoryID = 13, Name = "Corn Oil", PortionType = PortionType.Tablespoon, Calorie = 122, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\236.jpg" },
                new Nutrition { ID = 237, CategoryID = 13, Name = "Flour", PortionType = PortionType.Gram, Calorie = 364, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\237.jpg" },
                new Nutrition { ID = 238, CategoryID = 11, Name = "Sunnyside-up", PortionType = PortionType.Unit, Calorie = 95, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\238.jpg" },
                new Nutrition { ID = 239, CategoryID = 4, Name = "Red Wine", PortionType = PortionType.Glass, Calorie = 15, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\239.jpg" },
                new Nutrition { ID = 240, CategoryID = 4, Name = "White Wine", PortionType = PortionType.Glass, Calorie = 125, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\240.jpg" },
                new Nutrition { ID = 241, CategoryID = 4, Name = "Beer", PortionType = PortionType.Glass, Calorie = 155, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\241.jpg" },
                new Nutrition { ID = 242, CategoryID = 4, Name = "Champagne", PortionType = PortionType.Glass, Calorie = 95, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\242.jpg" },
                new Nutrition { ID = 243, CategoryID = 4, Name = "Vodka", PortionType = PortionType.Glass, Calorie = 96, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\243.jpg" },
                new Nutrition { ID = 244, CategoryID = 4, Name = "Rum", PortionType = PortionType.Glass, Calorie = 97, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\244.jpg" },
                new Nutrition { ID = 245, CategoryID = 4, Name = "Whiskey", PortionType = PortionType.Glass, Calorie = 98, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\245.jpg" },
                new Nutrition { ID = 246, CategoryID = 4, Name = "Tequila", PortionType = PortionType.Glass, Calorie = 98, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\246.jpg" },
                new Nutrition { ID = 247, CategoryID = 4, Name = "Gin", PortionType = PortionType.Glass, Calorie = 96, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\247.jpg" },
                new Nutrition { ID = 248, CategoryID = 9, Name = "Trout", PortionType = PortionType.Gram, Calorie = 119, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\248.jpg" },
                new Nutrition { ID = 249, CategoryID = 9, Name = "Halibut", PortionType = PortionType.Gram, Calorie = 111, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\249.jpg" },
                new Nutrition { ID = 250, CategoryID = 9, Name = "Sardines", PortionType = PortionType.Gram, Calorie = 208, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\250.jpg" },
                new Nutrition { ID = 251, CategoryID = 9, Name = "Mackerel", PortionType = PortionType.Gram, Calorie = 305, IsActive = true, Measurement = 100, Picture = "\\FoodPhotos\\251.jpg" },
                new Nutrition { ID = 252, CategoryID = 5, Name = "Snickers", PortionType = PortionType.Unit, Calorie = 280, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\252.jpg" },
                new Nutrition { ID = 253, CategoryID = 5, Name = "Twix", PortionType = PortionType.Unit, Calorie = 250, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\253.jpg" },
                new Nutrition { ID = 254, CategoryID = 5, Name = "Kit Kat", PortionType = PortionType.Unit, Calorie = 210, IsActive = true, Measurement = 1, Picture = "\\FoodPhotos\\254.jpg" }
                );
        }
    }
}
